apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: frontend-ui
        #image: acrboulderai.azurecr.io/frontend-ui:v1
        image: local-frontend:v6
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-ui-service
spec:
  #type: LoadBalancer
  type: ClusterIP
  selector:
    app: frontend-ui
  ports:
  - port: 80
    targetPort: 80