name: BoulderAI Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie najnowszego kodu z GitHuba
        uses: actions/checkout@v4

      - name: Logowanie do chmury Azure
        uses: azure/Login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Logowanie do prywatnego rejestru ACR
        run: az acr login --name acrboulderaifl

      - name: Budowanie i wysyłka obrazu Docker
        run: |
          docker build -t acrboulderaifl.azurecr.io/backend-api:${{ github.sha }} ./backend
          docker push acrboulderaifl.azurecr.io/backend-api:${{ github.sha }}
        
      - name: Konfiguracja dostępu do klastra AKS
        uses: azure/aks-set-context@v3
        with:
          resource-group: rg-boulderai-dev
          cluster-name: aks-boulderai-dev

      - name: Wdrożenie nowej wersji na produkcję!

        run: |
          kubectl set image deployment/backend-api backend-api=acrboulderaifl.azurecr.io/backend-api:${{ github.sha }}